# Generated by Django 3.1.12 on 2021-12-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='progress',
        ),
        migrations.AddField(
            model_name='account',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
