# Generated by Django 3.1.12 on 2021-12-23 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('citizen_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(1970, 1, 1))),
                ('place_of_birth', models.CharField(default='unknown', max_length=64)),
                ('place_of_origin', models.CharField(default='unknown', max_length=64)),
                ('permanent_address', models.CharField(blank=True, max_length=64)),
                ('temporary_address', models.CharField(blank=True, max_length=64)),
                ('religious', models.CharField(default='none', max_length=64)),
                ('occupation', models.CharField(default='none', max_length=256)),
                ('education', models.CharField(default='none', max_length=256)),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
