# Generated by Django 3.1.12 on 2021-12-25 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 15, 6, 47, 865395)),
        ),
    ]
