# Generated by Django 3.1.12 on 2021-12-24 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_auto_20211223_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1)),
        ),
    ]
