# Generated by Django 3.1.12 on 2021-12-25 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_citizen_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(max_length=1024),
        ),
    ]
