# Generated by Django 3.1.12 on 2021-12-25 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_auto_20211225_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 11, 7, 20, 587567, tzinfo=utc)),
        ),
    ]
