# Generated by Django 3.1.12 on 2021-12-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0005_auto_20211225_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
