# Generated by Django 3.1.12 on 2021-12-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_auto_20211225_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='education',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='occupation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='place_of_origin',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='religious',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
