# Generated by Django 3.1.12 on 2021-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_auto_20211225_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
